apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertdispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertdispatcher
  template:
    metadata:
      labels:
        app: alertdispatcher
    spec:
      containers:
        - name: alertdispatcher
          image: market-scanner-alertdispatcher:latest
          env:
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
