apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertdispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertdispatcher
  template:
    metadata:
      labels:
        app: alertdispatcher
    spec:
      containers:
        - name: alertdispatcher
          image: dg1223/market-scanner-alertdispatcher:latest
          imagePullPolicy: Always   # force pull latest image
          env:
            - name: APP_REDIS_HOST
              value: redis
            - name: APP_REDIS_PORT
              value: "6379"
