apiVersion: v1
kind: Secret
metadata:
  name: market-scanner-secrets
type: Opaque
data:
  # replace these base64 values with your actual secrets
  postgres_user: cG9zdGdyZXM=
  postgres_password: ZGJhZG1pbjEyMw==
  postgres_db: bWFya2V0ZGF0YQ==
  alphavantage_api_key: R0o1UlM1QUMzVVRZMExIUA==
  # redis_password: cmVkaXNhZG1pbjEyMw==
